### ISSUE TITLE
Can I use this?

### ISSUE THREAD

**Issue by ninjafootball07** [weeeBox/quake-one-in-unity#1]
I noticed there is no license, can I use this?

**Comment by weeeBox** [comment]
You should ask John Carmack

**Comment by ninjafootball07** [comment]
Sure that part GPL. I was curious about your work, is that under MIT or similar less restrictive or GPL with exception?

**Comment by weeeBox** [comment]
Feel free to use in any way

**Comment by ninjafootball07** [comment]
thx, mainly just learning
